[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyLiuno"
version = "0.2.1"
description = "说中文的编程语言，错误提示再也不怕了"
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "Ultra_FiD", email = "liziqian0715@163.com"}]
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
pyl = "PyLiuno.cli:main"